pretrained_model_path: "./checkpoints/fine-tuned/model"
output_dir: "output"


validation_data:
  prompts:
    - "Iron man is dribbling basketball on the beach"
  video_length: 4
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"


train_batch_size: 1
validation_steps: 100

# resume_from_checkpoint: ./checkpoints/followyourpose_checkpoint-1000


seed: 33
mixed_precision: 'no'
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: True
